### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by AlimovSV** [lodev09/react-native-exify#1]
```
❌  (node_modules/@lodev09/react-native-exify/ios/ExifyUtils.swift:59:23)

  57 |   addTagEntries(from: kCGImagePropertyTIFFDictionary, metadata: metadata, to: tags)
  58 |   addTagEntries(from: kCGImagePropertyPNGDictionary, metadata: metadata, to: tags)
> 59 |   addTagEntries(from: kCGImagePropertyHEICSDictionary, metadata: metadata, to: tags)
     |                       ^ 'kCGImagePropertyHEICSDictionary' is only available in iOS 13.0 or newer
  60 | 
  61 |   return tags as? [String: Any] ?? [:]
  62 | }
```

The deployment target for my project is 13.0, what is the reason of the error above?

**Comment by lodev09** [comment]
<img width="726" alt="Screenshot 2024-03-25 at 21 49 15" src="https://github.com/lodev09/react-native-exify/assets/6686328/3075914c-c429-4a5b-b889-290f392e7183">

Check your minimum deployments

**Comment by AlimovSV** [comment]
@lodev09 Thank you for response, but unfortunately it didn't help to me (

**Comment by lodev09** [comment]
I suggest you open your project in XCode and build from there. You can see the actual settings there.

**Comment by AlimovSV** [comment]
Yes, it is exactly what I did - changed the `Minimum Deployments` from `13.0` to `13.4`, cleanup the project and rebuild (my project is expo@49-bare based)

<img width="611" src="https://github.com/lodev09/react-native-exify/assets/4921904/620d4b34-4e8b-4e12-990d-8c17e65ba75e">

<img width="718" src="https://github.com/lodev09/react-native-exify/assets/4921904/69d96fe4-638d-4335-9075-95b5969d5a57">

**Comment by lodev09** [comment]
Hmmm, that's weird. The example project is also using expo (prebuild) which has a min deployment of 13.4  and it doesn't generate that error.

Can you try to prebuild it? Clone the repo and run:
```
yarn example setup
```

**Comment by AlimovSV** [comment]
Looks like the problem is that when I do
`
yarn add @lodev09/react-native-exify
npx pod-install
`
the Exify target is adding with 12.4 target
<img width="641" src="https://github.com/lodev09/react-native-exify/assets/4921904/7e65d373-c950-4ff4-bcc9-c9e055039c34">
so when I manually change this target to 13.0 the project build successfully, but it is not so good to manually change the deployment target for a library, what could be the reason of auto-assigning 12.4 for Exify? all other targets have 13.0

**Comment by lodev09** [comment]
Ahh.. I think this is the related issue:
https://github.com/facebook/react-native/issues/41053

What RN version are you on?

Exify Pod spec is getting the min version from RN
<img width="715" alt="Screenshot 2024-03-25 at 23 18 33" src="https://github.com/lodev09/react-native-exify/assets/6686328/18b16b1f-edd9-4abf-b4ae-d270f9d85529">

**Comment by AlimovSV** [comment]
0.72.6

**Comment by AlimovSV** [comment]
@lodev09 Thank you very much for assist.

**Comment by lodev09** [comment]
Should be fixed now! I just added a condition to that specific line so lower RN versions can still use this package.

Thank you for checking as well :)
https://github.com/lodev09/react-native-exify/commit/1a55b68a12b25c6707b4f5084bc467d3d253c36d
