### ISSUE TITLE
EXIF value types are not considered properly.

### ISSUE THREAD

**Issue by ER-lee-byeoksan** [lodev09/react-native-exify#2]
I'm trying to work around [orientation issue](https://github.com/mrousavy/react-native-vision-camera/issues/1891) from [react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera) with the following code snippet and I found that EXIF tag `Orientation` is not updated properly.
```ts
async function fixRotation(file: PhotoFile) {
  const uri = `file://${file.path}`;
  const tags = await Exify.readAsync(uri);

  if (tags?.Orientation != null && tags.Orientation !== 0) {
    return;
  }

  // See https://exiftool.org/TagNames/EXIF.html
  const Orientation = {
    portrait: 1,
    'portrait-upside-down': 3,
    'landscape-left': 8, // sensor orientation is 90
    'landscape-right': 6, // sensor orientation is 270
  }[file.orientation];

  await Exify.writeAsync(`file://${file.path}`, {
    Orientation,
  });
}
```

I think the reason is that `Orientation` tag accepts integer but the native module updates as floating point value.
https://github.com/lodev09/react-native-exify/blob/cb3c3151c7a5aaff192554a44f8bd0145357fdc0/android/src/main/java/com/lodev09/exify/ExifyModule.kt#L54-L66

I checked that the following code snippet updates `Orientation` tag well but I didn't test with iOS because I have no background with iOS dev.
```ts
        for ((valType, tag) in EXIFY_TAGS) {
          if (!tags.hasKey(tag)) continue

          val type = tags.getType(tag)

          when (type) {
            ReadableType.Boolean -> exif.setAttribute(tag, tags.getBoolean(tag).toString())
            ReadableType.Number ->
            when (valType) {
              "double" -> exif.setAttribute(tag, tags.getDouble(tag).toBigDecimal().toPlainString())
              else -> exif.setAttribute(tag, tags.getDouble(tag).toInt().toString())
            }
            ReadableType.String -> exif.setAttribute(tag, tags.getString(tag))
            ReadableType.Array -> exif.setAttribute(tag, tags.getArray(tag).toString())
            else -> exif.setAttribute(tag, tags.getString(tag))
          }
        }
```

**Comment by ER-lee-byeoksan** [comment]
Converting the value into string makes different target value (`Orientation 6` vs `Orientation 6.0`) and the result may depend on the devices (I cannot test all physical devices, you know). I tested it with Pixel_3a emulator and it didn't work. At least, I found a case where it does not update EXIF properly. So I suggested to make it more robust.

> I would recommend providing the orientation prop of the Camera instead
I'm not sure this is working as the issue is to make `orientation` prop works. Anyway, thanks for the suggestion. Forget about it because this is not the actual issue for this package.

> Modifying the Orientation works only for photo viewers that respects it
This is my exact use case so I needed to write EXIF `Orientation` tag.

If you didn't, could you test it with some emulators?

**Comment by lodev09** [comment]
Hmmm, okay that might make sense.. can you open up a PR plesae?

**Comment by devhubmarius** [comment]
I still facing the issue that the `Orientation` and some other e.g  `InterlaceType` cannot be updated on iOS.

Are there any updates?
