### ISSUE TITLE
Exif from Expo Media Library differs

### ISSUE THREAD

**Issue by maxih4** [lodev09/react-native-exify#4]
Hello,

is there any convenient way to take the Exif data from `expo-media-library` and write it to an image? The format differs a bit...

With the method from expo you get the following output:

`const exifRead = await MediaLibrary.getAssetInfoAsync(uri)`

`{"orientation":1,"duration":0,"height":2848,"isFavorite":false,"uri":"ph://B84E8479-475C-4727-A4A4-B77AA9980897/L0/001","width":4288,"creationTime":1255122560000,"isHidden":false,"filename":"IMG_0002.JPG","localUri":"file:///Users/maxih4/Library/Developer/CoreSimulator/Devices/15145CB0-C0DD-4864-9328-CFD5A9F7B16F/data/Media/DCIM/100APPLE/IMG_0002.JPG","mediaSubtypes":[],"location":{"latitude":"52.5249983","longitude":"13.3695038"},"id":"B84E8479-475C-4727-A4A4-B77AA9980897/L0/001","exif":{"ProfileName":"Adobe RGB (1998)","DPIWidth":72,"{Exif}":{"DateTimeOriginal":"2009:10:09 14:09:20","MaxApertureValue":5,"ComponentsConfiguration":[1,2,3,0],"ExposureBiasValue":0,"SceneCaptureType":0,"FNumber":5.6,"FocalLength":105,"ColorSpace":1,"PixelYDimension":2848,"FlashPixVersion":[1,0],"LightSource":9,"DateTimeDigitized":"2009:10:09 14:09:20","ISOSpeedRatings":[400],"PixelXDimension":4288,"ExifVersion":[2,2],"ExposureProgram":3,"Flash":0,"ExposureTime":0.005,"SensingMethod":2,"MeteringMode":5},"ColorModel":"RGB","Orientation":1,"{IPTC}":{"DigitalCreationTime":"140920","DigitalCreationDate":"20091009","ObjectName":"DSC_0010","DateCreated":"20091009","TimeCreated":"140920"},"{JFIF}":{"DensityUnit":1,"YDensity":72,"XDensity":72,"JFIFVersion":[1,0,1]},"PixelHeight":2848,"DPIHeight":72,"{TIFF}":{"ResolutionUnit":2,"Software":"QuickTime 7.6.3","PhotometricInterpretation":2,"DateTime":"2009:10:18 16:49:28","XResolution":72,"Orientation":1,"YResolution":72,"Model":"NIKON D90","Make":"NIKON CORPORATION"},"PixelWidth":4288,"Depth":8},"mediaType":"photo","modificationTime":1716538475058.227}`

When I try to write this exif to the image, it only works for some tags...

`const exifWrite = await writeAsync(exifRead)`

Exif read on that image:

`{"ResolutionUnit":2,"PixelYDimension":2848,"ColorModel":"RGB","ColorSpace":65535,"PixelXDimension":4288,"Orientation":1,"XResolution":72,"PixelHeight":2848,"PixelWidth":4288,"Depth":8,"ProfileName":"Adobe RGB (1998)","DPIWidth":72,"DPIHeight":72,"YResolution":72}`

Maybe I just cant think out of the box right now, but is there any easy way to pass the exif from expo to your library?

**Comment by lodev09** [comment]
Unfortunately, you will need to map the values you need manually. I intentionally normalized it based on Android tag names to make it easier to type and for consistency.
